name: Build msd-lite with static linking

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-msd-lite:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Clone and build with CMake (static linking)
      run: |
        git clone --recursive https://github.com/rozhuk-im/msd_lite.git
        cd msd_lite
        
        # 安装必要的依赖（包括静态库）
        sudo apt-get update
        sudo apt-get install -y cmake make gcc g++ build-essential \
          libssl-dev libcrypto++-dev libuv1-dev
        
        # 尝试安装静态库版本（如果可用）
        sudo apt-get install -y libssl-static || echo "libssl-static not available, will use dynamic linking for ssl"
        sudo apt-get install -y libcrypto++-static || echo "libcrypto++-static not available"
        sudo apt-get install -y libuv-static || echo "libuv-static not available"
        
        # 使用 CMake 构建，启用静态链接
        mkdir -p build
        cd build
        
        # 设置静态链接标志
        cmake .. \
          -DCMAKE_EXE_LINKER_FLAGS="-static" \
          -DCMAKE_FIND_LIBRARY_SUFFIXES=".a" \
          -DBUILD_SHARED_LIBS=OFF \
          -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc)
        
    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: msd-lite-static
        path: msd_lite/build/msd_lite
