name: Build msd-lite with static linking

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-msd-lite:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Clone and build with CMake (static linking)
      run: |
        git clone --recursive https://github.com/rozhuk-im/msd_lite.git
        cd msd_lite
        
        # 安装必要的依赖
        sudo apt-get update
        sudo apt-get install -y cmake make gcc g++ build-essential \
          libssl-dev libcrypto++-dev libuv1-dev
        
        # 使用 CMake 构建，启用静态链接
        mkdir -p build
        cd build
        
        # 设置静态链接标志
        cmake .. \
          -DCMAKE_EXE_LINKER_FLAGS="-static" \
          -DBUILD_SHARED_LIBS=OFF \
          -DCMAKE_BUILD_TYPE=Release
        
        make -j$(nproc)
        
        # 验证构建结果
        echo "构建完成，目录内容："
        ls -la
        echo "可执行文件："
        find . -type f -executable
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: msd-lite-static-build
        path: msd_lite/build/
        if-no-files-found: error
