name: Build msd-lite

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 允许手动触发

jobs:
  build-msd-lite:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Clone and build msd-lite
      run: |
        git clone https://github.com/rozhuk-im/msd_lite.git
        cd msd-lite
        sudo apt-get update
        sudo apt-get install -y meson ninja-build libcap-dev
        meson setup build
        meson compile -C build
        
        # 打包编译结果
        cd build
        tar -czvf msd-lite-binaries.tar.gz ./*

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: msd-lite-compiled
        path: msd-lite/build/msd-lite-binaries.tar.gz
